# Generated by Django 5.0.2 on 2024-03-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.manager'),
        ),
    ]
